spring:
    main:
      title: LCM
    devtools:
      livereload:
        enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: dbmasteruser
        password: ff3403209!!
        jdbc-url: jdbc:mysql://ls-54dcc89c57c67211c8b66ef1d2ffc0dff87e2d59.c7z5fqnnmwun.ap-northeast-2.rds.amazonaws.com:3306/LCM2_DEV
        minimum-idle: 5         #Connection Pool에 유지 가능한 최소 커넥션 개수
        maximum-pool-size: 10   #Connection Pool에 유지 가능한 최대 커넥션 개수
        idle-timeout: 30000     #Connection이 Poll에서 유휴상태(사용하지 않는 상태)로 남을 수 있는 최대 시간
        pool-name: LCM2HikariCP #Connction Pool 이름
        max-lifetime: 200000    #Connection의 최대 유지 가능 시간
        connection-timeout: 30000 #Pool에서 Connection을 구할 때 대기시간, 대기시간안에 구하지 못하면 Exception
    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          format_sql: true
    
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
      transport:
          protocol: smtp
      host: smtp.gmail.com
      port: 587
      username: 아이디
      password: 비밀번호

